export const DELETE_PERSON_REQUEST = "DELETE_PERSON_REQUEST";
export const SAVE_PERSON_REQUEST = "SAVE_PERSON_REQUEST";
export const FETCH_ROSTER_REQUEST = "FETCH_ROSTER_REQUEST";
export const UPDATE_ROSTER_REQUEST = "UPDATE_ROSTER_REQUEST";
export const ROSTER_SUCCESS = "ROSTER_SUCCESS";
export const ROSTER_FAILURE = "ROSTER_FAILURE";